### ISSUE TITLE
ReportStream OKTA Group for California Public Health needs to be updated.

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7471]
## Problem statement

When a user logs into the ReportStream website.  If they are part of the California Department of Public Health the daily downloads page is not current. The last update showing is on 10/22/2022.

[Write a short description of what you want to achieve with this task]

A month or two ago the daily files were moved from CA-dph.elr to ca-dph.elr-saphire  
The okta group needs to be update from the old location to the new location.

 [Links to documents, workflows, or list of key people and contact info]

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/24f07237-053b-48f6-9037-07ff7449d1e4)

## Acceptance criteria

- When a CA STLT user logs into ReportStream Website they will be able to access the most recent data files.

## To do

- Assign a team member to Research on how to do this in OKTA

**Comment by brandonnava** [comment]
@brick-green @chris-kuryak @avnieldravid Is this something Experience or Platform would have to look into?

**Comment by chris-kuryak** [comment]
@stephenkao @kevinhaube Do you think this an Experience responsibility or an API responsibility?

**Comment by stephenkao** [comment]
I do have admin privileges in Okta, but I'm not familiar with what's involved in updating groups here.  @kevinhaube if you know, maybe we could pair on this for my own edification?

**Comment by kevinhaube** [comment]
The Okta group name does not manage anything beyond the organization level. Utilizing the dropdown currently labeled `elr` in your screenshot, and changing it to `elr-saphire` (as below) will show them the data they are looking for.

<img width="1920" alt="Screen Shot 2023-01-11 at 2 10 04 PM" src="https://user-images.githubusercontent.com/4022304/211896368-78fccc68-bbf4-4e15-8717-904eeabf3038.png">

Notably, we _do not_ have the concept of a stored setting that tells us "hey, this organization prefers to load this receiver first" (i.e. a "primary" receiver setting). That is functionality that we could consider to mitigate any confusion around this in the future. However, I'd first recommend we ensure that any _unused_ receiver settings are pruned. I see both `elr` and `elr-test` which seem to not receive any data. In the case of organizations with only one receiver setting, the page will always load with that receiver selected.

**Comment by chris-kuryak** [comment]
@stephenkao @kevinhaube 
So is this as simple as removing the unused receiver settings from the CA Okta group?
Meaning, remove all except `elr-saphire`?
And if so, who would usually handle something like that?

**Comment by kevinhaube** [comment]
Yep! Admins have the ability to edit, clone, add, and delete these settings in the UI on our production site. From the organizations list, hitting Edit will take them to the page that shows organization settings, as well as sender and receiver service settings.

It is _also_ worth noting that these settings can vary from staging to production. That is, if I'm an admin and go into staging to create a setting that is being tested against (something I believe we have confirmed O&O engineers do), then that setting _only_ exists in staging. So O&O could, and should, form some type of SOP around the addition, updating, and removal of features in our various environments to avoid the issue of stale sender or receiver service settings in our environments. This is pretty important moving forward, as we'll be populating a production dropdown much like this one, but for senders, on our Validator page.

**Comment by chris-kuryak** [comment]
@brandonnava @brick-green See above response from Kevin. It appears if you go into product and remove the unused receiver settings for CA and leave only `elr-saphire`that should solve that issue. Let me know if this is not the solution you were looking for.

@kevinhaube I will connect with you on creating a ticket on the enhancement you noted in the second half of your comment.

**Comment by kevinhaube** [comment]
@chris-kuryak I went ahead and opened a ticket outlining a fairly low-lift way we can ensure we aren't setting any non `active` settings, though it's noted in said ticket that we still can't isolate a preferred active setting. We can work with O&O engineers to figure out if there's a _need_ for multiple `active` settings, and if so, scope out any necessary further enhancements!

**Comment by brandonnava** [comment]
Fixed
